name: Discord-Reuse

on:
  push:
    branches:
      - production

  workflow_dispatch:

jobs:
  deploy:
    uses: Matrix-Labs-Development/matrix_Actions-Runners/.github/workflows/discord.yml@production
    secrets: inherit